### ISSUE TITLE
Users should be able to lock their notes

### ISSUE THREAD

**Issue by adregan** [adregan/notes#3]
A user should be able to lock their notes so that the app only displays encrypted notes

A lock action should:
- [x] if unsaved changes #12 
- [x] Confirm the event with a popup #11
- [x] Map over the application store and replace decrypted data with empty object #13 
- [x] Create an action to replace the key with an unlocked key #13
- [x] update the little lock icon

**Comment by adregan** [comment]
The little lock flips back and forth now
